name: Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Prepare a docker container for build
        uses: docker/build-push-action@v3
        with:
          context: tools/docker
          file: tools/docker/slim.dockerfile
          load: true
          tags: spike-rt:slim
          push: false
          cache-from: type=gha,scope=slim
          cache-to: type=gha,mode=max,scope=slim
      - name: Build test(QEMU)
        uses: addnab/docker-run-action@v3
        with:
          image: spike-rt:slim
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            # Avoid a git error saying "fatal: detected dubious ownership in repository at ..."
            git config --global --add safe.directory \* 
            ./scripts/build-test-qemu.sh
      - name: Build test
        uses: addnab/docker-run-action@v3
        with:
          image: spike-rt:slim
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            # Avoid a git error saying "fatal: detected dubious ownership in repository at ..."
            git config --global --add safe.directory \* 
            ./scripts/build-test.sh
      - name: Build all sample applications
        uses: addnab/docker-run-action@v3
        with:
          image: spike-rt:slim
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            # Avoid a git error saying "fatal: detected dubious ownership in repository at ..."
            git config --global --add safe.directory \* 
            ./scripts/build-samples.sh
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: TestApp
          path: |
            build/obj-primehub_test/asp
            build/obj-primehub_test/asp.bin
            build/obj-primehub_test/asp.syms
